# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0019_auto_20171130_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Decimal with two places eg. 200.00', max_digits=6)),
                ('currency', models.CharField(help_text='The currency of the APC value eg. GBP or USD.', max_length=25)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Section')),
            ],
            options={
                'ordering': ('section__journal', 'value', 'currency'),
            },
        ),
        migrations.CreateModel(
            name='WaiverApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=25)),
                ('made', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('made', 'status'),
            },
        ),
    ]
