# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0002_auto_20180221_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverapplication',
            name='rationale',
            field=models.TextField(null=True),
        ),
    ]
