# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20171130_1115'),
        ('apc', '0003_waiverapplication_rationale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Decimal with two places eg. 200.00', max_digits=6)),
                ('currency', models.CharField(help_text='The currency of the APC value eg. GBP or USD.', max_length=25)),
                ('recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('section_apc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apc.SectionAPC')),
            ],
        ),
    ]
