# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0004_articleapc'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleapc',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('waived', 'Waived'), ('paid', 'Paid'), ('nonpay', 'Non Payment')], default='new', max_length=25),
        ),
    ]
