# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0005_articleapc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleapc',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
