# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0006_articleapc_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverapplication',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
