# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0007_waiverapplication_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverapplication',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submission.Article'),
        ),
    ]
