# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0008_auto_20180226_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverapplication',
            name='rationale',
            field=models.TextField(null=True, verbose_name='Supporting Information'),
        ),
    ]
