# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-12 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0038_auto_20200428_0803'),
        ('apc', '0009_auto_20200116_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStaffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receives_notifications', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
                ('staffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='billingstaffer',
            unique_together=set([('staffer', 'journal')]),
        ),
    ]
