# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0009_auto_20200116_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleapc',
            name='invoiced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleapc',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('waived', 'Waived'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('nonpay', 'Non Payment')], default='new', max_length=25),
        ),
    ]
