# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-11 09:55
from __future__ import unicode_literals

from django.db import migrations


def update_apc_status(apps, schema_editor):
    ArticleAPC = apps.get_model('apc', 'ArticleAPC')
    ArticleAPC.objects.filter(status='nopay').update(status='nonpay')

class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0009_auto_20200116_1154'),
    ]

    operations = [
        migrations.RunPython(
            update_apc_status,
            reverse_code=migrations.RunPython.noop
        ),
    ]
