# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-18 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0010_update_apc_status'),
        ('apc', '0010_auto_20200511_1129'),
        ('apc', '0010_auto_20200512_0950'),
    ]

    operations = [
    ]
