# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0011_auto_20200618_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.PositiveIntegerField()),
            ],
        ),
    ]
