# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0011_auto_20200618_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstaffer',
            name='type_of_notification',
            field=models.CharField(choices=[('ready', 'Ready for Invoicing'), ('invoiced', 'Invoice Sent'), ('paid', 'Invoice Paid')], default='ready', max_length=15),
        ),
    ]
