# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_auto_20200428_0803'),
        ('apc', '0011_auto_20200618_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='APCDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Decimal with two places eg. 200.00', max_digits=8)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
            ],
        ),
        migrations.AlterField(
            model_name='articleapc',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Decimal with two places eg. 200.00', max_digits=8),
        ),
    ]
