# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_auto_20200428_0803'),
        ('apc', '0012_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Journal'),
        ),
    ]
