# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_auto_20200428_0803'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apc', '0012_billingstaffer_type_of_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingstaffer',
            unique_together=set([('staffer', 'journal', 'type_of_notification')]),
        ),
    ]
