# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0013_discount_journal'),
        ('apc', '0013_auto_20200629_1251'),
    ]

    operations = [
    ]
