# Generated by Django 4.2.11 on 2024-09-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apc', '0015_alter_waiverapplication_reviewer'),
        ('apc', '0015_auto_20211109_1028'),
    ]

    operations = [
    ]
